WITH CTE AS(

  SELECT HIRE_DATE,
  TO_TIMESTAMP(HIRE_DATE) AS HIRE_DATE_TS,
  DATE(TO_TIMESTAMP(HIRE_DATE)) AS HIRE_DATE_FROM_TS,
  MONTH(TO_TIMESTAMP(HIRE_DATE)) AS HIRE_DATE_MONTH,
  dayname(TO_TIMESTAMP(HIRE_DATE)) AS DAY_NAME,
  CASE WHEN   MONTH(TO_TIMESTAMP(HIRE_DATE)) IN ('12','1','2') THEN 'WINTER'
  WHEN  MONTH(TO_TIMESTAMP(HIRE_DATE)) IN ('3','4','5') THEN 'SUMMER' ELSE 'SPRING' END AS SEASON
  FROM {{ source('AG_SOURCE_DEMO', 'EMPLOYEES') }}

)
SELECT * FROM CTE