WITH CTE AS(

  SELECT HIRE_DATE,
  TO_TIMESTAMP(HIRE_DATE) AS HIRE_DATE_TS,
  DATE(TO_TIMESTAMP(HIRE_DATE)) AS HIRE_DATE_FROM_TS,
  MONTH(TO_TIMESTAMP(HIRE_DATE)) AS HIRE_DATE_MONTH,
  dayname(TO_TIMESTAMP(HIRE_DATE)) AS DAY_NAME,

    {{get_season('HIRE_DATE')}} as season
  
  FROM {{ source('AG_SOURCE_DEMO', 'EMPLOYEES') }}

)
SELECT * FROM CTE